import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";

const myFont = localFont({
  src: '../../public/fonts/Cleanow/Cleanow.ttf'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${myFont.className} justify-items-center`} >
        <div className="max-w-[1440px] w-full m-auto z-50 bg-no-repeat bg-cover bg-center"   style={{ backgroundImage: "url('/images/bg.png')"}} >
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
